// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.1
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMyServiceCall = "/helloworld.v1.MyService/Call"

type MyServiceHTTPServer interface {
	Call(context.Context, *Request) (*Response, error)
}

func RegisterMyServiceHTTPServer(s *http.Server, srv MyServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/my-api/{id}", _MyService_Call0_HTTP_Handler(srv))
}

func _MyService_Call0_HTTP_Handler(srv MyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Request
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMyServiceCall)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Call(ctx, req.(*Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type MyServiceHTTPClient interface {
	Call(ctx context.Context, req *Request, opts ...http.CallOption) (rsp *Response, err error)
}

type MyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMyServiceHTTPClient(client *http.Client) MyServiceHTTPClient {
	return &MyServiceHTTPClientImpl{client}
}

func (c *MyServiceHTTPClientImpl) Call(ctx context.Context, in *Request, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/my-api/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMyServiceCall))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
